# Generated by Django 4.2.1 on 2023-07-21 08:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Reservar', '0004_alter_bus_patente_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fechaCreacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
    ]
