# Generated by Django 4.2.1 on 2023-07-21 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservar', '0005_reserva_fechacreacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidad',
            name='asiento',
        ),
        migrations.AddField(
            model_name='asientos',
            name='disponibilidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Reservar.disponibilidad'),
        ),
        migrations.AlterField(
            model_name='asientos',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
